name: ERPNext CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ERPNext
        uses: actions/checkout@v4

      - name: Checkout frappe_docker
        uses: actions/checkout@v4
        with:
          repository: vijayreddy8/ERP-devops-project
          ref: develop
          path: frappe_docker

      - name: Build ERPNext Docker image
        working-directory: frappe_docker
        run: docker buildx bake erpnext
